version: "3.8"

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"            # Open at http://localhost:8081
    environment:
      PMA_HOST: db           # <— your MySQL/MariaDB service name
      PMA_PORT: 3306
      PMA_ARBITRARY: 1       # allow selecting a different host if needed
      UPLOAD_LIMIT: 256M
      MEMORY_LIMIT: 512M
      TZ: Africa/Casablanca
    depends_on:
      - db
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: sofascore_php
    working_dir: /var/www/app
    volumes:
      - ./app:/var/www/app
    depends_on:
      - db

  composer:
    image: composer:2
    container_name: sofascore_composer
    working_dir: /var/www
    volumes:
      - ./app:/var/www
    depends_on:
      - php
    environment:
      COMPOSER_ALLOW_SUPERUSER: "1"

  nginx:
    image: nginx:1.25
    container_name: sofascore_nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  db:
    image: mysql:8.0
    container_name: sofascore_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sofascore
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
